---
- name: Check for root password
  changed_when: false
  stat:
    path: /usr/local/etc/mysql-password
  register: mysql_password

- name: create root password
  command: "pwgen 25 1"
  register: generated_password

- name: Read root-password
  when: mysql_password.stat.exists
  slurp:
    src: "{{ item }}"
  with_items:
    - /usr/local/etc/mysql-password
  register: slurp_result

- name: Write root password to cli client configuration file
  when: mysql_password.stat.exists
  blockinfile:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0600
    create: yes
    block: |
      [client]
      password={{ slurp_result.results.0.content|b64decode|trim }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK: MariaDB root password"
  loop_control:
    label: "{{ item.path }}"
  with_items:
    - path: /root/.my.cnf
      owner: root
      group: wheel
    - path: "{{ ansible_user_dir }}/.my.cnf"
      owner: "{{ ansible_user_uid }}"
      group: "{{ ansible_user_gid }}"
