---
- name: Confiure garb (garb.cnf)
  when: mariadb.galera.arbitrator == True
  template:
    src: garb.cnf
    dest: /etc/default/garb.cnf
    owner: root
    group: root
    mode: 0644
  notify: Restart garbd
