- name: Add MariaDB repo key
  apt_key:
    url: https://mariadb.org/mariadb_release_signing_key.asc
    state: present

- name: add mariadb repo
  apt_repository:
    repo: "deb http://mirror2.hs-esslingen.de/mariadb/repo/10.3/ubuntu focal main"
    state: present
    filename: /etc/apt/sources.list.d/mariadb.list

- name: Install MariaDB
  when: ansible_distribution == 'Ubuntu'
  apt:
    name: [mariadb-server, python3-pymysql, pwgen]
    update_cache: True
