- block:

  - name: Add MariaDB repository key
    apt_key:
      url: "{{ mariadb.repository.apt.key_url }}"

  - name: Add MariaDB repository
    apt_repository:
      repo: "{{ mariadb.repository.apt.repository }}"
      filename: /etc/apt/sources.list.d/mariadb.list

  when: ansible_distribution == 'Ubuntu'

- name: Install MariaDB
  when:
    - ansible_distribution == 'Ubuntu'
    - mariadb.galera.arbitrator
  apt:
    name:
      - mariadb-server
      - python3-pymysql
    update_cache: True

- name: Install garb
  when:
    - ansible_distribution == 'Ubuntu'
    - mariadb.galera.arbitrator
  apt:
    name:
      - galera-arbitrator-3
    update_cache: True
