---
- name: Load OS-specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - main.yml
      paths:
        - 'vars'

- name: Install MariaDB
  ansible.builtin.import_tasks: install.yaml

- name: Configure MariaDB
  ansible.builtin.import_tasks: config_db.yaml

- name: Configure Galera Arbitrator (garb)
  ansible.builtin.import_tasks: config_garb.yaml

- name: Configure Galera Cluster
  ansible.builtin.import_tasks: galera.yaml

- name: Configure MySQL CLI client
  ansible.builtin.import_tasks: client_config.yaml

- name: Handle MariaDB users
  ansible.builtin.import_tasks: users.yaml

- name: Handle MariaDB databases
  ansible.builtin.import_tasks: databases.yaml

- name: Set up MariaDB database backups
  ansible.builtin.import_tasks: backup.yaml
