---
- name: Start MariaDB
  service:
    name: mysql-server
    state: started
  register: mysqld_service_result

- name: Restart MariaDB
  service:
    name: mysql-server
    state: restarted
  when: not (mysqld_service_result is defined and mysqld_service_result.changed)
