---
- name: Converge
  hosts: all
  environment:
    GITHUB_ACTIONS: "maybe"
    ANSIBLE_HASH_BEHAVIOUR: merge
  vars:
    mariadb:
      databases:
        molecule:
          name: molecule
      users:
        molecule:
          username: molecule
          password: supersecretpassword
          privileges:
            molecule: molecule.*:all
          hosts:
            molecule:
              - 127.0.0.1
              - localhost
  tasks:
    - name: "Include ansible-proserver-mariadb"
      ansible.builtin.include_role:
        name: "ansible-proserver-mariadb"
