---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Get MariaDB version
      register: mariadb_version
      changed_when: no
      ansible.builtin.command:
        cmd: mariadb --version

    - name: Assert MariaDB client is installed
      ansible.builtin.assert:
        that:
          - mariadb_version.rc == 0
        fail_msg: "MariaDB client binary is missing"
        success_msg: "MariaDB client binary is present"

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Assert MariaDB service is active
      ansible.builtin.assert:
        that:
          - ansible_facts['services']['mariadb.service']['state'] == "running"
        fail_msg: "MariaDB service is not active"
        success_msg: "MariaDB service is active"

    - name: Run test query via mysql
      register: mariadb_ping
      changed_when: false
      ansible.builtin.command:
        cmd: "mysql --execute 'SELECT 1'"

    - name: Assert MariaDB responds to queries
      ansible.builtin.assert:
        that:
          - mariadb_ping.rc == 0
        fail_msg: "MariaDB did not respond to the SELECT 1 probe"
        success_msg: "MariaDB responded to the SELECT 1 probe"

    - name: Check that molecule database exists
      register: mariadb_molecule_db
      changed_when: false
      ansible.builtin.command:
        argv:
          - mysql
          - --execute
          - "SHOW DATABASES LIKE 'molecule';"

    - name: Assert molecule database exists
      ansible.builtin.assert:
        that:
          - "'molecule' in mariadb_molecule_db.stdout"
        fail_msg: "Database 'molecule' does not exist"
        success_msg: "Database 'molecule' exists"

    - name: Test login as molecule user
      register: mariadb_molecule_login
      changed_when: false
      ansible.builtin.command:
        argv:
          - mysql
          - -u
          - molecule
          - -psupersecretpassword
          - -D
          - molecule
          - --execute
          - SELECT 1

    - name: Assert molecule user can log in
      ansible.builtin.assert:
        that:
          - mariadb_molecule_login.rc == 0
        fail_msg: "User 'molecule' could not log in to database 'molecule'"
        success_msg: "User 'molecule' can log in to database 'molecule'"

    - name: Test write and read as molecule user
      register: mariadb_molecule_write_read
      changed_when: false
      ansible.builtin.command:
        argv:
          - mysql
          - -u
          - molecule
          - -psupersecretpassword
          - -D
          - molecule
          - --execute
          - "CREATE TABLE IF NOT EXISTS molecule_verify (id INT PRIMARY KEY AUTO_INCREMENT, value VARCHAR(50)); INSERT INTO molecule_verify (value) VALUES ('hello'); SELECT value FROM molecule_verify ORDER BY id DESC LIMIT 1;"

    - name: Assert molecule user can write to and read from database
      ansible.builtin.assert:
        that:
          - mariadb_molecule_write_read.rc == 0
          - "'hello' in mariadb_molecule_write_read.stdout"
        fail_msg: "User 'molecule' could not write to and read from database 'molecule'"
        success_msg: "User 'molecule' can write to and read from database 'molecule'"
