---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get MariaDB version
      register: mariadb_version
      changed_when: no
      ansible.builtin.command:
        cmd: mariadb --version

    - name: Display PostgreSQL version
      ansible.builtin.debug:
        var: mariadb_version.stdout
