---
name: Test
run-name: Run ansible-lint and molecule tests on the role
on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install ansible-lint
        run: pip install ansible ansible-lint

      - name: Ansible-lint
        run: ansible-lint

  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gofrolist/molecule-action@v2
